default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  encoding: utf8
  host: localhost

development:
  <<: *default
  database: db/progress_job_demo_dev.sqlite3

test:
  <<: *default
  database: db/progress_job_demo_test.sqlite3

production:
  <<: *default
  database: db/progress_job_demo.sqlite3

